export const SUCCESS_AXIOS_PROFESSION = 'SUCCESS_AXIOS_PROFESSION';
export const SUCCESS_AXIOS_PROFESSION_CHANGE =
	'SUCCESS_AXIOS_PROFESSION_CHANGE';
export const SUCCESS_AXIOS_SPHERE = 'SUCCESS_AXIOS_SPHERE';
export const SUCCESS_AXIOS_SPHERE_CHANGE = 'SUCCESS_AXIOS_SPHERE_CHANGE';
export const SUCCESS_AXIOS_VACANCYTEMPLATE = 'SUCCESS_AXIOS_VACANCYTEMPLATE';
export const SUCCESS_AXIOS_VACANCYTEMPLATE_CHANGE =
	'SUCCESS_AXIOS_VACANCYTEMPLATE_CHANGE';
export const SUCCESS_AXIOS_CATEGORY = 'SUCCESS_AXIOS_CATEGORY';
export const SUCCESS_AXIOS_CATEGORY_CHANGE = 'SUCCESS_AXIOS_CATEGORY_CHANGE';
export const SUCCESS_AXIOS_SKILL = 'SUCCESS_AXIOS_SKILL';
export const SUCCESS_AXIOS_SKILL_CHANGE = 'SUCCESS_AXIOS_SKILL_CHANGE';

export const ERROR = 'ERROR';
