// export const SUCCESS_AXIOS = 'SUCCESS_AXIOS';
export const SUCCESS_AXIOS_SKILL = 'SUCCESS_AXIOS_SKILL';
export const SUCCESS_AXIOS_CATEGORY = 'SUCCESS_AXIOS_CATEGORY';
export const SUCCESS_AXIOS_VACANCYTEMPLATE = 'SUCCESS_AXIOS_VACANCYTEMPLATE';
export const SUCCESS_AXIOS_PROFESSION = 'SUCCESS_AXIOS_PROFESSION';
export const SUCCESS_AXIOS_SPHERE = 'SUCCESS_AXIOS_SPHERE';
export const ERROR = 'ERROR';
