export const SUCCESS_AXIOS = 'SUCCESS_AXIOS_VACANCY!!';
export const SUCCESS_AXIOS_LIST = 'SUCCESS_AXIOS_VACANCY_LIST!!';
export const GET_CANDIDATES = 'GET_CANDIDATES_VACANCY!!';
export const ADD_VACANCY = 'ADD_VACANCY!!';
export const ADD_INFO = 'ADD_INFO_VACANCY!!';
export const ERROR = 'ERROR';
